# Generated by Django 4.0.4 on 2022-05-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('message', models.TextField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Student_Feedback_Forms/Contact_Forms',
            },
        ),
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('middleName', models.CharField(blank=True, max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=10)),
                ('rollNumber', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('BSc', 'Bachelor of Science'), ('IT', 'Bachelor of Information Technology'), ('BTECH', 'Engineering'), ('MSc', 'Master of Science'), ('HUMAN', 'Humanities')], max_length=5)),
                ('year', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Registered_Student_Names',
            },
        ),
    ]
