# Generated by Django 4.0.4 on 2022-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
