# Generated by Django 4.0.4 on 2022-05-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_position', models.CharField(max_length=80)),
                ('position_priority', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Ballot position list',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Student Feedback/Contact Forms'},
        ),
        migrations.AlterModelOptions(
            name='student_registration',
            options={'verbose_name_plural': 'Registered Student Names'},
        ),
    ]
