# Generated by Django 4.0.4 on 2022-05-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_position_name_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='position_name',
            new_name='Positions',
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name_plural': 'Ballot Position List'},
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='name_of_position',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='position_priority',
            new_name='priority',
        ),
    ]
