# Generated by Django 4.0.4 on 2022-05-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_position_name_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bio', models.TextField(max_length=300)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.positions')),
            ],
        ),
    ]
