# Generated by Django 4.0.4 on 2022-05-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_positions_priority_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name_plural': 'Candidate List'},
        ),
        migrations.CreateModel(
            name='Logged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student_registration')),
            ],
            options={
                'verbose_name_plural': 'Voted Student List',
            },
        ),
    ]
