# Generated by Django 4.0.4 on 2022-05-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_candidate_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.CharField(choices=[('1', 'ON THE VOTING'), ('2', 'OFF THE VOTING')], max_length=1)),
                ('messaging', models.TextField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Voting Status Control',
            },
        ),
    ]
